config/routes.rb
Rails.application.routes.draw do
  get "signup" => "pages#signup", as: "signup"
   get "signin" => "pages#signin", as: "signin"
   get "home" => "pages#home", as: "home"
   get "list" => "pages#list", as: "list"
   get "attemptlogin" => "pages#attemptlogin", as: "attempt"
   get "profile" => "pages#profile", as: "profile"
   get "aftersignin" => "users/sessions#signin", as: "after_signin"
   get "viewuser/(:id)" => "pages#viewuser", as: "viewuser"
   get "signout" => "pages#signout", as: "signout"
   get "gobacktoprofile" => "pages#currentuser", as: "cu"
   get "eventspage" => "pages#events", as: "events"

   root to: "pages#home"
  devise_for :users, controllers: { sessions: "users/sessions", registrations: 'users/registrations' }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :debug
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  

  def debug
  	ap session
  	ap params
  end

  def after_sign_in_path_for(resource)
  	
      profile_path
    
  end
   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :building, :info, :email, :password, :avatar, :avatar_cache, :current_password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :building, :info, :email, :password, :avatar, :avatar_cache, :current_password) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def home
    if @signedin == true or current_user != nil
      redirect_to profile_path
    end
  end
  def attemptlogin
    redirect_to home_path
    @log = true
  end
  def signup
    if @signedin == true or current_user != nil
      redirect_to profile_path
    end
  end
  def signin
    if @signedin == true or current_user != nil
      redirect_to profile_path
    end
  end
  def list
    if @signedin == true or current_user != nil
      redirect_to profile_path
    end
  	@users = User.all
  end
  def viewuser
    # @id = User.find(params[:id])
    @id = params[:id]
    redirect_to profile_path

  end
  def profile
    # Creates linked list 
    @users = User.all
    
    @cuser = current_user
    if params[:id] != nil
      @cuser = User.find(params[:id])
     
    end

    params[:id] = nil
    @signedin=true
  
    
    
    # for loading list of nearby users
  end
  def events
  end
  def signout
    sign_out current_user
    @id = 0
    @signedin = false
    redirect_to home_path
    
  end

  def currentuser
    params[:id] = nil
    redirect_to profile_path
  end
   
  protect_from_forgery with: :exception
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  def passthru
    super
  end

  # GET|POST /users/auth/twitter/callback
  def failure
    super
  end

  # protected

  # The path used when OmniAuth fails
  def after_omniauth_failure_path_for(scope)
    super(scope)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  # protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
  

  def new
  end
#   GET /resource/sign_up
  
  

  

#   POST /resource
  def create
    super
  end

#   GET /resource/edit
  def edit
    super
  end

#   PUT /resource
  def update
    super
  end

#   DELETE /resource
  def destroy
    super
  end

#   GET /resource/cancel
#   Forces the session data which is usually expired after sign
#   in to be expired now. This is useful if the user wants to
#   cancel oauth signing in/up in the middle of the process,
#   removing all OAuth session data.
  def cancel
    super
  end

#   protected

#   If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :attribute
    params.require(:user).permit(:name, :info, :avatar, :avatar_cache)
  end
#   If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :attribute
    params.require(:user).permit(:name, :info, :avatar, :avatar_cache)
  end
#   The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

#   The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
  before_filter :configure_permitted_parameters, if: :devise_controller?

 

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    redirect_to signin_path
    
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
    params.require(:user).permit(:name, :info)
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  # protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Commonwebapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <title>Home</title>

  <style>
    .bg-hero {
    text-align: center;
    font-size: 18pt;
    }
    .inner {

    /*float: right;*/
    margin: 0 auto;
    margin-top: 0;
    z-index: 999;
    background-color: white;
    opacity: 10%;
    min-height: 3em;
    width: 100%;
    position: fixed;
    box-shadow: .1em .1em .1em grey;




    }
    .btn {
    padding-right: 3em;
    padding-left: .5em;
    padding-bottom: .1em;
    padding-top: .1em;
    }
    .buffer {
    height:4em;
    width: 100%;
    }
    .lettering {
    opacity: 100%;
    font-size: 13pt;
    text-align: left;
    width: 10em;
    margin: 0em;
    }
    .lettering2 {
    opacity: 100%;
    font-size: 13pt;

    padding-right: 5em;
    color: white;
    margin-right:0em;
    width: 15em;
    }
    .buff {
    height: .75em;
    }
    .logo {

    opacity: 100%;
    margin-right: 28em;
    }
    .l, .si, .su{
    opacity: 100%;
    font-size: 18px;
    margin-right: 5em;
    color: black;
    font-weight: lighter;
    font-style: arial;
    }
    .headerimage{


    margin-top: 0%;
    float: right;
    height: 32em;
    width: 55em;



    }
    .otext {
    background-image: url("http://orig15.deviantart.net/70d4/f/2012/108/8/6/teal_windows_8_bubbles_background_by_gifteddeviant-d4wkij8.png");
    min-height: 7em;
    text-align: center;
    font-size: 26px;
    display:inline-block;
    color: white;
    font-weight: lighter;
    padding-bottom: 3em;




    }
    .buffer {
    height: 3.2em;
    }
    .one, .two, .three {
    height: 11em;
    width: 11em;
    border-radius: 10em;
    text-align: center;


    }
    .blogone {

    font-weight: lighter;

    text-align: center;
    margin: 0 auto;
    width: 11em;
    padding-top: 2em;
    height: 6em;
    }
    .blog {




    }
    .title {
    text-align: center;
    font-size: 18pt;
    font-weight: lighter;
    padding-bottom: 2em;


    }
    .buffed {
    height: 10em;

    }
    .descrip {
    width: 11em;
    padding-bottom: 2em;
    text-align: center;
    margin: 0 auto;

    }
    .bgheroimage {
    background-image: url("assets/bcg_hero_membership_community.jpg");
    background-size: 133.655em 75em;

    font-size: 16px;
    height: 40em;
    }
    .testimonial {
    margin: 0 auto;

    }

    .cup1 {
    width: 5em;

    }
    .options {
    width: 17em;
    margin-right: 0;

    }
    .l {
    margin-right: 0;
    }
    .su {
    margin-left: 0;
    }
    .median {
    height: 1em;
    }
    .blue {
    height: 10em;
    }
    .center {
    height: 10em;
    }
    .centered {
    margin: 0 auto;
    min-height: 30em;
    width: 70em;
    }
    .colu {
    text-align: center;
    }


  </style>
  
</head>
<body>
 

    <div class="bg-hero">
        <div class="inner">
           <div class = "buff">
            </div>

            
              <%= link_to image_tag('top_logo.png'), home_path, {:class => "logo"} %>
            
              
            
            
              <%=link_to 'Sign Up', signup_path, {:class => "su"} %>   <%=link_to 'Sign In', signin_path, {:class => "si"} %>    <%=link_to 'Members', list_path, {:class => "l"} %> 
            
            
        
        </div>
        <div class = "col-sm-12 bgheroimage">
        </div>
       <!-- 
        <%= image_tag("bcg_hero_membership_community", :class => "headerimage")%>
       -->
        <!-- <div class "wraphi">
        <%= image_tag("bcg_hero_membership", :class => "headerimage")%>
        </div>
         -->


        
        
           
        
    </div>



    <div class = "col-sm-12 otext">
    <div class = "buffer">
            </div>
                <p>
                At Common, you’re not just a member — you’re part of a community that cares.
                <p>
                Here you can view other members in your area, see their interests, and contact them before you move in.</p>
                </p>
    </div>
    
    
    <%= image_tag("Screen Shot 2015-11-16 at 3.32.18 PM", :class => "testimonial")%>
    
    
    
    <!-- REPLACE BLOG POSTS AS MORE IMPORTANT ONES APPEAR -->
    
    <div class = "col-sm-12 title">
        <p>
        <%= link_to "Check out our blog", "http://blog.hicommon.com/" %>
        </p>
    </div>
    <div class = "col-sm-12">
    </div>
     
    
    
   <div class = "colu">
    <div class = "col-sm-2">
    </div>
    <div class = "col-sm-2 blog">
      
      <%= link_to image_tag('ONBOARD.jpg', :class => "one"), "http://blog.hicommon.com/2015/11/how-we-onboard-members/" %>
      <div class ="blogone">
      
      <%= link_to "How We Onboard Members", "http://blog.hicommon.com/2015/11/how-we-onboard-members/" %>
      </div>
      <div class = "descrip">
      At Common, we’ve set out to improve the way we live together by providing fully furnished homes with flexible month-to-month terms at an all-in-one price. As we built out our first property...
      </div>
      
    
    </div>
    <div class = "col-sm-1 blue">
    </div>
   

  
    <div class = "col-sm-2 blog">
      <p>
      <%= link_to image_tag('1162.jpg', :class => "two"), "http://blog.hicommon.com/2015/10/hello-1162-pacific-street/" %>

      <div class ="blogone">
      <%= link_to "Hello 1162 Pacific Street", "http://blog.hicommon.com/2015/10/hello-1162-pacific-street/" %>
      </div>
      <div class = "descrip">
      We started Common to address the need for housing that is flexible, user-friendly, and community-driven. Our mission is to rethink housing from the ground up, answering the question of...
      </div> 
      </p>
    </div>
    
     <div class = "col-sm-1 blue">
    </div>
    
    
    <div class = "col-sm-2 blog">
      
      <%= link_to image_tag('moneybag.jpg', :class => "three"), "http://blog.hicommon.com/2015/07/common-raises-7-35m-to-make-housing-better/" %>
      <div class ="blogone">
      <%= link_to "Common Raises $7.35M to Make Housing Better", "http://blog.hicommon.com/2015/07/common-raises-7-35m-to-make-housing-better/" %>
      </div>
      <div class = "descrip">
      Choosing an apartment is the most expensive decision many of us make every year. Yet we face time pressure, limited and distorted information and an all-around poor customer experience...
      </div>
    </div>
  </div>

   
    
    






</body>
</html>

app/views/pages/list.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
<style>
    .bg-hero {
    text-align: center;
    font-size: 18pt;
    }
    .inner {

    float: right;
    margin: 0 auto;
    margin-top: 0;
    z-index: 999;
    background-color: white;
    opacity: 10%;
    min-height: 3em;
    width: 100%;
    position: fixed;
    box-shadow: .1em .1em .1em grey;


    }
    .logo {

    opacity: 100%;
    margin-right: 28em;
    }
    .l, .si, .su {
    opacity: 100%;
    font-size: 18px;
    margin-right: 5em;
    color: black;
    font-weight: lighter;
    font-style: arial;
    }
    .buff {
    height: .75em;
    }
    .list {
    text-align: center;
    display:block;
    }
    .buffer {
    height: 10em;
    }
    .people {
    height: 20em;
    background-color: white;


    }
    .options {
    width: 17em;
    margin-right: 0;

    }
    .l {
    margin-right: 0;
    }
    .su {
    margin-left: 0;
    }
    .median {
    height: 1em;
    }
    .margin { 
    height: 7em;
    }
    .display {
    height:  15em;
    width: 15em;
    }

</style>
</head>
<body>
<div class="bg-hero">
<div class="inner">
            
            <div class = "buff">
            </div>

            
              <%= link_to image_tag('top_logo.png'), home_path, {:class => "logo"} %>
            
              
            
            
              <%=link_to 'Sign Up', signup_path, {:class => "su"} %>   <%=link_to 'Sign In', signin_path, {:class => "si"} %>    <%=link_to 'Members', list_path, {:class => "l"} %> 
            
           
</div>
</div>
<div class = "buffer">
            </div>

<div class = "list">

<%= render "/users/list/list" %>

</div>

</body>
</html>

app/views/pages/originalprofile.html.erb
.background {
    /*height: 100%;*/
    
    
    
  }
  .atliens {
    text-align: center;
    font-size: 18pt;
    height: 29em;
    border-top-color: black;
    border-top-style: solid;
    border-top-width: .1em;
    border-bottom-color: black;
    border-bottom-style: solid;
    border-bottom-width: .1em;
    margin-top: 0em;
    background-color: white;
  }
  .list {
    font-size: 9pt;
    border-width: .2em;
    border-style: solid;
    border-color: black;
    /*TIMES 2 EM BECAUSE HALF PT FONT*/
    margin-left: 1em;
    margin-top: 3em;
    height: 51.35em;
    width: 12em;
    overflow: auto;
    padding: 0;
    background-color: rgba(230,230,230,0.4);
    position: relative;
  }
  .profile {
    font-size: 9pt;
    border-width: .2em;
    border-style: solid;
    border-color: black;
    
   /* margin-left: 10em;
    margin-top: 2em;*/
    height: 16em;
    width: 16em;
    padding:0;
  }
  .commoninfo {
    font-size: 9pt;
    border-width: .2em;
    border-style: solid;
    border-color: black;
    
    height: 12em;
    /*width: 76em;*/
    width: 50em;
    /*margin-left: 2em;
    margin-top: 2em;
    margin-bottom: 2em;*/
    text-align: left;
    padding: 0;
    background-color: rgba(230,230,230,0.4);
    
    
  }
  .label {
    font-size: 9pt;
    border-width: .2em;
    border-style: solid;
    border-color: black;
    border-radius: .7em;
    height: 4em;
    width: 8em;
    margin-left: 2em;
    margin-top: 2em;
    color: black;

    
   
  }
  .sect {
    font-size: 9pt;
    border-width: .2em;
    border-style: solid;
    border-color: black;
    
    height: 38.35em;
   /* width: 66em;*/
   /* margin-left: 2em;
    margin-top: 2em;*/
    width: 50em;
    text-align: left;
    background-color: rgba(230,230,230,0.4);
    
    padding: 0;
    margin-top: 1em;

    

  }
  .run {
    margin-top: 1em;
    padding:1em;
    margin-left: 2em;
    margin-right: 1em;
    margin-bottom: 1em;
    font-size: 12pt;
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-weight: 475;
    background-color: rgba(230,230,230,0.6);
    width: 33.2em;
    height: 10em;

    

  }
  .wrapper1{
    margin-left:7em;
    margin-top: 1.5em;
    width: 8em;
    padding: 0;
    
  }
  .events{
    font-size: 9pt;
    width: 16em;
    height: 26em;
    margin-top: 1em;
    border-width: .2em;
    border-style: solid;
    padding:0;
    border-color: black;
  }
  .wrapper2{
    width: 25em;
    margin-top: 1.5em;
    padding: 0;
    margin-left: .5em;
  }
  .listheader{
    margin-top: 0em;
    border-width: .1em;
    border-bottom-width: .2em;
    border-bottom-style: solid;
    border-bottom-color: black;
    padding: 0;
    margin-bottom: 1em;
    width: 11.7em;
    height: 3em;
    background-color: rgba(255,255,255, 1);
    position: fixed;
    z-index: 199;


  }
  .signout{
    font-size: 9pt;
    width: 16em;
    height: 7.35em;
    margin-top: 1em;
    border-width: .2em;
    border-style: solid;
    border-color: black;
  }
  .button {
    margin-top: .79em;
    font-size: 12pt;
  }
  .eventheader{
    border-bottom-width: .133em;
    border-bottom-style: solid;
    border-bottom-color: black;
    height: 3.1em;
    font-size: 12pt;

  }
  .bio{
    font-weight: 300;
    color: black;
  }
  .run1{
    margin-top: 0em;
    padding:1em;
    margin-left: 2em;
    margin-right: 1em;
    margin-bottom: 1em;
    font-size: 12pt;
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-weight: 475;
    background-color: rgba(230,230,230,0.6);
    width: 33.2em;
    height: 15.35em;
  }
  .outer{
    margin: 1em 1em 1em 1em;
    padding: 0;
    height: 3.82em;
    background-color: rgba(230,230,230,0.6);
    width: 47.7em;
    text-align: center;


  }
  .info{
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-weight: 200;
    font-size: 18pt;
    color: black;
  }
  .lightlist{
    margin-left: 2em;
    padding-bottom: 1em;
    height: 58em;
    padding-top: 1em;
    padding-left: 0em;
    padding-right: 0em;
    background-color: rgba(230,230,230,0.6);
    margin-top: 4em;
  }
  .topbuff{
    height: 2em;
  }
















!-- <div class = "col-sm-12 topbuff">

    </div>  

  
  <!-- <section class="section section-community full-width"> -->
        <div class="col-sm-12 atliens">
    <div class = "col-sm-8 wrapper1">
        <div class ="col-sm-2 profile">
          Profile Image

        </div>
        <div class = "col-sm-2 events">
          <div class = "col-sm-12 eventheader">
                <p></p>
                Events
            </div>

        </div>
        <div class = "col-sm-2 signout">

            <div class = "col-sm-12 button">
              <%= link_to "Sign Out", signout_path %>
            </div>

            <div class = "col-sm-12 button">
              <%= link_to current_user.name, cu_path %>
            </div>

        </div>

    </div>


    
    <div class = "col-sm-4 wrapper2">
        <div class ="col-sm-8 commoninfo">
          <div class = "col-sm-12 outer">
          <div class = "col-sm-12 info">


          <%= @cuser.name %>
          </div>
          </div>
          <div class = "col-sm-12 outer">
          <div class = "col-sm-12 info">

          1162 Pacific Street
          </div>
          </div>
          
          


        </div>
        
        <div class ="col-sm-8 sect">
   
          <div class = "col-sm-12 run">
          <div class = "col-sm-12 bio">

          How I got here: <%= @cuser.info %>
          </div>
          </div>
          <div class = "col-sm-12 run1">
          <div class = "col-sm-12 bio">

          Interests: <%= @cuser.info %>
          </div>
          </div>

        </div>


     </div>
        <div class ="col-sm-2 list">
          <div class = "col-sm-12 listheader">
              <p></p>
              Members
          </div>
          <p></p>
          <div class = "col-sm-8 lightlist">
          <%= render "users/list/list2" %>


        </div>
        
       </div>
        

    </div>
  

app/views/pages/signin.html.erb
<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <title>Sign In</title>

  <style>
  
    .bg-hero {
    text-align: center;
    font-size: 18pt;


    }

    .btn {
    padding-right: 3em;
    padding-left: 3em;
    padding-bottom: 1.5em;
    padding-top: 1.5em;
    }
    .form {
    font-size: 14pt;

    }
    .buffer {
    height:1em;
    width: 100%;
    }
    .inner {

    /*float: right;*/
    margin: 0 auto;
    margin-top: 0;
    z-index: 999;
    background-color: white;
    opacity: 10%;
    min-height: 3em;
    width: 100%;
    position: fixed;
    box-shadow: .1em .1em .1em grey;


    }
    .logo {

    opacity: 100%;
    margin-right: 28em;
    }
    .l, .si, .su {
    opacity: 100%;
    font-size: 18px;
    margin-right: 5em;
    color: black;
    font-weight: lighter;
    font-style: arial;
    }
    .buff {
    height: .75em;
    }
    .run {

    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-weight: lighter;
    font-size: 12pt;
    }
    .buffs {
    height: .7em;
    }
    .field {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-weight: lighter;
    }




    .options {
    width: 17em;
    margin-right: 0;

    }
    .l {
    margin-right: 0;
    }
    .su {
    margin-left: 0;
    }
    .median {
    height: 1em;
    }
    .margin {
    height: 8em;
    }

 
</style>
</head>
<body>

    <div class="bg-hero">
        <div class="inner">
           <div class = "buff">
            </div>

            
              <%= link_to image_tag('top_logo.png'), home_path, {:class => "logo"} %>
            
              
            
            
              <%=link_to 'Sign Up', signup_path, {:class => "su"} %>   <%=link_to 'Sign In', signin_path, {:class => "si"} %>    <%=link_to 'Members', list_path, {:class => "l"} %> 
            
            
        
        </div>
        <div class = "col-sm-12 margin">
        </div>
        <div class = "col-sm-12 run">
        <p>
        </p>

        <%= render "users/sessions/new" %>
        </div>
       
        

    </div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>